### ISSUE TITLE
Some problem on that structure modification of pre-trained model when use loratorch

### ISSUE THREAD

**Issue by hacker-jerry** [Baijiong-Lin/LoRA-Torch#1]
Hi, I am having problems with your library as I am new to lora.

I have a pre-trained model class and the individual layers defined.

How do I do if I want to use lora to fine tune one of the embedding?

I changed the corresponding layer in model.py to `self.emb_lora = lora.Embedding(l_dim, embed_dim, r=16, lora_alpha=32)` as instructed in the readme. But when loading the checkpoint, I found that the corresponding key is missing (lora_a, lora_b are missing because the structure is original at the time of training),how should I fix it?

**Comment by hacker-jerry** [comment]
If I do this, I print the fine-tuned model weights and find that the original W is gone and only lora_a and lora_b remain, what went wrong?

**Comment by Baijiong-Lin** [comment]
> I changed the corresponding layer in model.py to `self.emb_lora = lora.Embedding(l_dim, embed_dim, r=16, lora_alpha=32)` as instructed in the readme. But when loading the checkpoint, I found that the corresponding key is missing (lora_a, lora_b are missing because the structure is original at the time of training),how should I fix it?

lora parameters (i.e., lora_a and lora_b) are new and do not exist in the pre-trained checkpoint. Thus, you should load the pre-trained checkpoint as follows,
`model.load_state_dict(torch.load('ckpt_pretrained.pt'), strict=False)`


> If I do this, I print the fine-tuned model weights and find that the original W is gone and only lora_a and lora_b remain, what went wrong?

After `lora.mark_only_lora_as_trainable(model)`, only lora parameters are trainable.

**Comment by hacker-jerry** [comment]
Thanks @Baijiong-Lin ! But if the pre-training weights are loaded directly, do we still have to modify the original model structure? If the model structure is modified, where is the W+∆W operation in LoRA reflected?

**Comment by Baijiong-Lin** [comment]
$W=W+AB$ is executed before ``forward()``, then calling ``forward()`` with $W$, and finally $W=W-AB$ is executed after  ``forward()``.

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
