### ISSUE TITLE
About Code Efficiency Improvement

### ISSUE THREAD

**Issue by xbingsun** [Baijiong-Lin/LoRA-Torch#2]
Hello, thanks for such a useful code! However, when I use lora in a multi-head attention layer, I find that it is slow when inferring.
I looked at the source code and suspected that it was due to the need to re-merge the parameters of the lora and recover them each time the forward function is called (the corresponding functions are `self.merge_lora_param()` and `self.sub_lora_data()`).

So, can I please remove the above two directives from the forward and move them to the end of the `__init__ ` function at the same time?  I'm not sure this operation will have any bad effects.

**Comment by xbingsun** [comment]
I just found out that there is a `lora_train` function in the source code, can I call `model.lora_train(mode=False)`,to fulfill the above requirement?

**Comment by Baijiong-Lin** [comment]
when inference, you should call ``model.eval()`` first, then ``model.lora_train(mode=False)`` will be automatically called.

**Comment by xbingsun** [comment]
Yes, I did call `model.eval()` and now the inference is still slow, do you have any suggestions for improvement?

**Comment by Baijiong-Lin** [comment]
if you have called ``model.eval()``, the lora matrixs will be merged only once and ``self.merged`` is always ``True`` until ``model.train()`` is called.

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
