### ISSUE TITLE
a question about nn.MultiheadAttention

### ISSUE THREAD

**Issue by ChushanZhang** [Baijiong-Lin/LoRA-Torch#6]
Hello there, thank you for this amazing work!

Since reading your README, it seems that MultiheadAttention is supported. Are there any documents referring to this?

In my understanding, the in_proj_weight represents the weights_qkv, similar to the linear_layer in other implementations.

However, when I try to use lora-torch at this step, it results in the following error: "TypeError: cannot assign 'loralib.layers.Embedding' as parameter 'in_proj_weight' (torch.nn.Parameter or None expected)."

Please let me know if it is incorrect to replace the w_qkv with lora or any instruction is much appreciated.
```         
w_qkv = blk.attn.in_proj_weight
w_qkv_shape = w_qkv.shape
lora_embedding = loralib.Embedding(w_qkv_shape[0], w_qkv_shape[1], r=r)
blk.attn.in_proj_weight = lora_embedding
```

**Comment by ChushanZhang** [comment]
as I was told we should replace the nn.MultiheadAttention with lora-torch.MultiheadAttention, so I changed the code to following:

```
        for layer_index, resblock in enumerate(clip_model.visual.transformer.resblocks):
            if hasattr(resblock, 'attn'):
                multihead = resblock.attn
                embed_dim = multihead.embed_dim
                num_heads = multihead.num_heads

                lora_multihead = loratorch.MultiheadAttention(embed_dim, num_heads, r=r)
                resblock.attn = lora_multihead
```

However, it seems the loss becomes much higher than before. Perhaps this kind of writing break the pre-train weights somehow.

So if there are any comments would be much appreciated!

**Comment by ChushanZhang** [comment]
the problem has been solved! 
We should relace the LoRA layer then load agin the pre-train weights!

**Comment by Impression2805** [comment]
Hi @PoopBear1 
I have the same problem with you that pre-train weights have been broken after applying LoRA. Could be kindly share your solution of "releasing the LoRA layer and then loading again the pre-train weights"? Many thanks!

**Comment by vietvo89** [comment]
Hi @PoopBear1, how did you load the pre-train weights after replacing the LoRA layer?

**Comment by vietvo89** [comment]
@PoopBear1, I follow your code snippet and load the weights as follow:
```
r = 8
for i, resblock in enumerate(model.visual.transformer.resblocks):
    if hasattr(resblock, 'attn'):
        multihead = resblock.attn
        embed_dim = multihead.embed_dim
        num_heads = multihead.num_heads
        lora_multihead = lora.MultiheadAttention(embed_dim, num_heads, r=r)
        lora_multihead.load_state_dict(resblock.attn.state_dict(),strict=False)
        resblock.attn = lora_multihead
```

Then I fine-tuned as follow:

```
# Tokenizer and text embeddings
tokenizer = open_clip.get_tokenizer("ViT-B-32")
classnames = train_dataset.classes
text_inputs = tokenizer([f"a photo of a {label}" for label in classnames]).cuda()
with torch.no_grad():
    text_features = model.encode_text(text_inputs)
    text_features = text_features / text_features.norm(dim=-1, keepdim=True)

optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4)
model.train()

# training loop
for epoch in range(5):
    total_loss = 0
    correct = 0
    total = 0
    for images, labels in tqdm(train_loader):
        images, labels = images.cuda(), labels.cuda()
        image_features = model.encode_image(images)
        image_features = image_features / image_features.norm(dim=-1, keepdim=True)
        logits = image_features @ text_features.t()
        loss = nn.CrossEntropyLoss()(logits, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

        preds = logits.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

        lora.register_model_param_after_backward(model)

    acc = correct / total
    print(f"Epoch {epoch+1}: Loss={total_loss:.4f}, Accuracy={acc:.4f}")
```

But the model did not learn or update the weights properly. Loss and accuracy were almost the same.

**Comment by vietvo89** [comment]
Hi @Baijiong-Lin , thank you for your response here https://github.com/Baijiong-Lin/LoRA-Torch/issues/9#issuecomment-2949683751. Follow the approach above, I can replace the original `attn` by your `MultiheadAttention`. But I'm not sure why the model was not updated correctly and the loss remained unchanged. I don't know what's wrong with my code. What do you reckon?

**Comment by vietvo89** [comment]
Hi @Baijiong-Lin , you can reproduce my results by running this [notebook ](https://www.kaggle.com/code/vietvo89/finetune-openclip-with-loratorch). Basically, I tested your `Linear` and the one from `loralib` and found that both implementations worked well. But `loralib` does not support `attn`, so I gave your implementation a shot. Unfortunately, I might make mistakes when employing your `MultiheadAttention` but I did not know where the bugs were. If debugging this problem successfully, this notebook can serve as a demo of using `loratorch` with `open clip`.

**Comment by Baijiong-Lin** [comment]
> Hi [@Baijiong-Lin](https://github.com/Baijiong-Lin) , you can reproduce my results by running this [notebook ](https://www.kaggle.com/code/vietvo89/finetune-openclip-with-loratorch). Basically, I tested your `Linear` and the one from `loralib` and found that both implementations worked well. But `loralib` does not support `attn`, so I gave your implementation a shot. Unfortunately, I might make mistakes when employing your `MultiheadAttention` but I did not know where the bugs were. If debugging this problem successfully, this notebook can serve as a demo of using `loratorch` with `open clip`.

@vietvo89 Sorry for late reply. I have checked your code. The default value for ``batch_first`` in nn.MultiheadAttention is False, but openclip sets it to True in some attn layers. With the following modifications, the code now runs correctly.

```
lora_multihead = lora.MultiheadAttention(embed_dim, num_heads, r=r, enable_lora=enable_lora, batch_first=multihead.batch_first)
```

**Comment by vietvo89** [comment]
@Baijiong-Lin, excellent! Thanks for your help. It saved my life 👍 . I cannot figure out how `open_clip` sets `batch_first` of some `attn` layers to `True`. I genuinely appreciate your help!

**Comment by Baijiong-Lin** [comment]
@vietvo89 May I include your code in the README as an example? I will certainly acknowledge your contribution.

**Comment by vietvo89** [comment]
@Baijiong-Lin. Absolutely, I modified the code and create a new [colab notebook](https://colab.research.google.com/drive/1yfkS4cAxnTajt2LlEOcgLh5c_hIeooS0?usp=sharing) to combine both `mlp` and `attn`. This makes the code more convenient and flexible for selecting one or both of them. So please use the `Colab version` instead.

**Comment by Baijiong-Lin** [comment]
@vietvo89 thanks~ I think the best way to apply ``lora.Linear`` and ``lora.MultiheadAttention`` is as follows.

![Image](https://github.com/user-attachments/assets/a09e8c24-4938-444a-8721-dd3db6b91b55)

**Comment by vietvo89** [comment]
Hi @Baijiong-Lin , I have changed the code. To provide a thorough example, could you provide a reference for your new way? I just want to include a link to explain why you add new arguments.

**Comment by Baijiong-Lin** [comment]
@vietvo89 I have provided the code [here](https://github.com/Baijiong-Lin/LoRA-Torch/blob/main/examples/Finetune_open_clip_with_LoRA_Torch_on_CIFAR10.ipynb). These arguments are in ``nn.MultiheadAttention`` or ``nn.Linear``. It is necessary to ensure they use the same values when replacing nn layer to loratorch one. Thus, explicitly assigning values is the best way.
