### ISSUE TITLE
lora.Conv1d cannot work

### ISSUE THREAD

**Issue by HelloWorldLTY** [Baijiong-Lin/LoRA-Torch#8]
Hi, thanks for your work. I tired to replace nn.Conv1d by lora.Conv1d. However, it seems that we received mis-shape error:

RuntimeError: shape '[768, 4, 15]' is invalid for input of size 691200

My original nn.Conv1d has the following parmateres:

nn.Conv1d(in_channels=4, out_channels=half_dim, kernel_size=15, padding = 7)

What is the correct way to implement lora.Conv1d here? Thanks.

**Comment by Baijiong-Lin** [comment]
I have fixed this problem. You can try it again.

**Comment by HelloWorldLTY** [comment]
Thanks, it works!
